version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/fantasy_football
      - DEBUG=true
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm run dev

  db:
    image: timescale/timescaledb:latest-pg14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fantasy_football
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dagster:
    build:
      context: ./data
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./data:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/fantasy_football
    depends_on:
      - db
    command: dagster dev

volumes:
  postgres_data: 