version: '3.8'

services:
  # Backend API service
  api:
    build:
      context: ..
      dockerfile: ./scripts/Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/fantasy_football
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ../:/app
    depends_on:
      - db
    command: python scripts/run_server.py --host 0.0.0.0 --port 8000
    networks:
      - fantasy-network

  # Database service
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fantasy_football
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fantasy-network

networks:
  fantasy-network:
    driver: bridge

volumes:
  postgres_data: 