version: '3.8'

services:
  agent_orchestrator:
    build:
      context: ..
      dockerfile: agent_system/Dockerfile
    container_name: fantasy_football_agents
    env_file:
      - ./.env
    volumes:
      - ..:/app
      - agent_outputs:/app/agent_system/outputs
    command: python -m agent_system.agent_runner --initialize --daemon
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
  
  agent_dashboard:
    build:
      context: ..
      dockerfile: agent_system/Dockerfile
    container_name: fantasy_football_agent_dashboard
    ports:
      - "8080:8080"
    volumes:
      - agent_outputs:/app/agent_system/outputs
    command: python -m agent_system.dashboard
    restart: unless-stopped
    depends_on:
      - agent_orchestrator
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO

  redis:
    image: redis:alpine
    container_name: fantasy_football_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  agent_outputs:
  redis_data: 