name: Code Quality Check

on:
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install rich autopep8 psycopg2-binary
          
      - name: Run code quality checks
        run: |
          # Get changed files
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -E '\.py$|\.js$|\.ts$|\.tsx$|\.jsx$' || true)
          
          if [ -z "$CHANGED_FILES" ]; then
            echo "No code files changed. Skipping quality checks."
            exit 0
          fi
          
          # Run quality checks
          python agent_system/validate_code_quality.py --all --detailed
          VALIDATION_RESULT=$?
          
          # If validation failed with errors, try to fix them
          if [ $VALIDATION_RESULT -ne 0 ]; then
            echo "Attempting to fix common issues..."
            python agent_system/code_quality_autofix.py
            
            # Check again after fixes
            python agent_system/validate_code_quality.py --all --detailed
            VALIDATION_RESULT=$?
          fi
          
          exit $VALIDATION_RESULT
      
      - name: Comment on PR
        if: github.event_name == 'pull_request' && failure()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '⚠️ **Code Quality Check Failed**\n\nThe automated code quality check has found issues with your code. Please fix these issues before merging.\n\nYou can run `python agent_system/code_quality_autofix.py` locally to attempt automatic fixes.'
            }); 